 [template]
src = "production.tmpl"
dest = "/config/production.json"
keys = [
    "/configuration/logger/level",
    "/configuration/swagger/jsonPath",
    "/configuration/swagger/uiPath",
    "/configuration/swagger/port",
    "/configuration/kafka/clientId",
    "/configuration/kafka/brokers",
    "/configuration/kafka/topic",
    "/configuration/bbox/area/square/km/limit"
]
