openapi: 3.0.1
info:
  title: exporter-trigger
  description: Service that responsible for activating the export geopackage process
  version: 1.0.0
servers:
  - url: http://localhost:80
paths:
  /exportGeopackage:
    post:
      tags:
        - Geopackage Exporter
      summary: Trigger export geopackage process
      operationId: exportGeopackage
      requestBody:
        $ref: "#/components/requestBodies/ExportProcessBody"
      responses:
        200:
          description: OK
          content: {}
        500:
          description: Server Error
          content: {}
      x-codegen-request-body-name: body

components:
  requestBodies:
    ExportProcessBody:
      description: Export geopackage request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exportProcess'
  schemas:
    layerOption:
      required:
        - url
        - exportType
      type: object
      properties:
        url:
          type: string
          description: URL of tile server that needs to be downloaded
        exportType:
          type: string
          enum: [raster, vector]
          description: >
            Export Type:
             * `raster` - Geopackage of raster tiles
             * `vector` - Geopackage of vector features
      example:
        url: http://test/geoserver/ows?service=wms
        exportType: raster

    exportProcess:
      required:
        - bbox
        - fileName
        - directoryName
        - exportedLayers
      type: object
      properties:
        fileName:
          type: string
          description: the file name to be created on shared folder
        directoryName:
          type: string
          description: the directory name to be created on shared folder
        bbox:
          type: array
          description: Bounding box corners (lower left, upper right)=[minx,miny,maxx,maxy] in crs units as array
        exportedLayers:
          type: array
          items:
            $ref: "#/components/schemas/layerOption"

      example:
        fileName: test_file
        directoryName: test_directory
        bbox: [22.5,45,45,67.5]
        exportedLayers:
          - url: http://test/geoserver/ows?service=wms
            exportType: raster



