openapi: 3.0.1
info:
  title: exporter-trigger
  description: Service that responsible for activating the export geopackage process
  version: 1.0.0
servers:
  - url: http://localhost:80
paths:
  /exportGeopackage:
    post:
      tags:
        - Geopackage Exporter
      summary: Trigger export geopackage process
      operationId: exportGeopackage
      requestBody:
        $ref: '#/components/requestBodies/ExportProcessBody'
      responses:
        200:
          description: OK
          content: {}
        500:
          description: Server Error
          content: {}
      x-codegen-request-body-name: body
  /exportStatus:
    get:
      tags:
        - Geopackage Execution Status
      summary: Get the status of export jobs
      operationId: getGeopackageExecutionStatus
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/exportStatus'
        500:
          description: Server Error
          content: {}

components:
  requestBodies:
    ExportProcessBody:
      description: Export geopackage request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/exportProcess'
  schemas:
    layerOption:
      required:
        - url
        - exportType
      type: object
      properties:
        url:
          type: string
          description: URL of tile server that needs to be downloaded
        exportType:
          type: string
          enum: [raster, vector]
          description: >
            Export Type:
             * `raster` - Geopackage of raster tiles
             * `vector` - Geopackage of vector features
      example:
        url: http://test/geoserver/ows?service=wms
        exportType: raster

    exportProcess:
      required:
        - bbox
        - fileName
        - directoryName
        - exportedLayers
        - sizeEst
      type: object
      properties:
        fileName:
          type: string
          description: the file name to be created on shared folder
          pattern: '^[a-zA-Z0-9_-]+$'          
        directoryName:
          type: string
          description: the directory name to be created on shared folder
          pattern: '^[a-zA-Z0-9_-]+$'          
        bbox:
          type: array
          items:
            type: number
          description: Bounding box corners (lower left, upper right)=[minx,miny,maxx,maxy] in crs units as array
        exportedLayers:
          type: array
          items:
            $ref: '#/components/schemas/layerOption'
        sizeEst:
          type: number
          description: the file estimated size (Mb)

      example:
        fileName: test_file
        directoryName: test_directory
        bbox:
          [
            34.811938017107494,
            31.95475033759175,
            34.82237261707599,
            31.96426962177354,
          ]
        exportedLayers:
          - url: http://test/geoserver/ows?service=wms
            exportType: raster
        sizeEst: 30

    exportStatus:
      type: array
      items:
        type: object
        properties:
          taskId:
            type: string
            description: unique task id
          userId:
            type: string
            description: user unique id
          directoryName:
            type: string
            description: the directory where the file is stored
          fileName:
            type: string
            description: file name
          sizeEst:
            type: number
            description: file's estimated size
          realSize:
            type: number
            description: file's real size
          polygon:
            type: object
            properties:
              type:
                type: string
              coordinates:
                type: array
                items:
                  type: array
                  items:
                    type: array
                    items:
                      type: integer
            description: the exported polygon
          status:
            type: string
            enum: [Pending, In-Progress, Completed, Failed]
            description: export status
          link:
            type: string
            description: file's full location
          creationDate:
            type: string
            description: export's creation date
          lastUpdateTime:
            type: string
            description: export's update time
          expirationTime:
            type: string
            description: export's expiration time
          progress:
            type: number
            description: export's progress %

        example:
          taskId: acb2dd1f-c7cc-4600-bf31-fb42ff387ee2
          userId: tester
          directoryName: saas
          fileName: z
          realSize: 0.12
          polygon:
            type: Polygon,
            coordinates:
              [
                [
                  [34.7862839772771, 32.0933739075861],
                  [34.7865314250815, 32.0933739075861],
                  [34.7865314250815, 32.093634611523],
                  [34.7862839772771, 32.093634611523],
                  [34.7862839772771, 32.0933739075861],
                ],
              ]
          status: Completed
          link: /saas/z.GPKG
          creationDate: 2020-11-10T12:09:01.000Z
          lastUpdateTime: 2020-11-10T12:09:22.000Z
          expirationTime: 2020-12-10T12:09:01.000Z
          progress: 100
